name: jaspberry
version: '0.1'
summary: Autonomous Jasperchain box for mining Jaspercoins
description: |
  Turns a Raspberry PI 3 into a mining node of the Jasperchain network.
  More info, please refer to https://gitlab.com/xgem/jasperberry

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cli:
    command: jasperchain-cli
    plugs:
      - network
  util:
    command: jasperchain-util
  miner:
    command: jasperchaind jasper15@warpit.tarpat.com:15222 -daemon
    plugs:
      - home
      - network
    daemon: simple
    stop-command: jasperchain-cli jasper15 stop
    restart-condition: always

parts:
  jasperchain-cli:
    plugin: dump
    source: .

  jasperchain-util:
    plugin: dump
    source: .

  jasperchaind:
    plugin: dump
    source: .

  libs:
    plugin: nil
    stage-packages:
      - libdb4.8-dev
      - libdb4.8++-dev
