name: jaspberry
version: '0.1'
summary: Autonomous Jasperchain box for mining Jaspercoins
description: |
  Turns a Raspberry PI 3 into a mining node of the Jasperchain network.
  More info, please refer to: https://gitlab.com/xgem/jasperberry

confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  jasperchaind:
    source: .
    plugin: dump
    organize:
      contrib/snap/jasperchaind: /usr/local/bin/jasperchaind
      contrib/snap/jasperchain-cli: /usr/local/bin/jasperchain-cli
      contrib/snap/jasperchain-util: /usr/local/bin/jasperchaind-util

apps:
  node:
    command: jasperchaind jasper15@warpit.tarpat.com:15222 -datadir=~/jasperchain -daemon
    daemon: simple
    plugs:
       - network-bind
       - home 
  cli:
    command: jasperchain-cli jasper15 -datadir=~/jasperchain 
    plugs:
      - network
      - home
